import { ObjectType } from '@/types';

export const MockObjects: ObjectType[] = [
  {
    image: '/images/preview.png',
    title: 'Five Palms many chars in the title',
    price: 49.923,
    share: 1,
    type: 'rent',
  },
  {
    image: '/images/preview.png',
    title: 'Five Palms 2',
    price: 49.923,
    share: 1,
    type: 'object',
  },
  {
    image: '/images/preview.png',
    title: 'Five Palms 3',
    price: 49.923,
    share: 1,
    type: 'rent',
  },
  {
    image: '/images/preview.png',
    title: 'Five Palms 4',
    price: 49.923,
    share: 1,
    type: 'object',
  },
  {
    image: '/images/preview.png',
    title: 'Five Palms 5',
    price: 49.923,
    share: 1,
    type: 'rent',
  },
  {
    image: '/images/preview.png',
    title: 'Five Palms 6',
    price: 49.923,
    share: 1,
    type: 'object',
  },
  {
    image: '/images/preview.png',
    title: 'Five Palms 7',
    price: 49.923,
    share: 1,
    type: 'rent',
  },
  {
    image: '/images/preview.png',
    title: 'Five Palms 8',
    price: 49.923,
    share: 1,
    type: 'object',
  },
  {
    image: '/images/preview.png',
    title: 'Five Palms 9',
    price: 49.923,
    share: 1,
    type: 'rent',
  },
  {
    image: '/images/preview.png',
    title: 'Five Palms 10',
    price: 49.923,
    share: 1,
    type: 'object',
  },
  {
    image: '/images/preview.png',
    title: 'Five Palms 11',
    price: 49.923,
    share: 1,
    type: 'rent',
  },
  {
    image: '/images/preview.png',
    title: 'Five Palms 12',
    price: 49.923,
    share: 1,
    type: 'object',
  },
  {
    image: '/images/preview.png',
    title: 'Five Palms 13',
    price: 49.923,
    share: 1,
    type: 'rent',
  },
  {
    image: '/images/preview.png',
    title: 'Five Palms 14',
    price: 49.923,
    share: 1,
    type: 'object',
  },
  {
    image: '/images/preview.png',
    title: 'Five Palms 15',
    price: 49.923,
    share: 1,
    type: 'rent',
  },
  {
    image: '/images/preview.png',
    title: 'Five Palms 16',
    price: 49.923,
    share: 1,
    type: 'object',
  },
  {
    image: '/images/preview.png',
    title: 'Five Palms 17',
    price: 49.923,
    share: 1,
    type: 'rent',
  },
  {
    image: '/images/preview.png',
    title: 'Five Palms 18',
    price: 49.923,
    share: 1,
    type: 'object',
  },
  {
    image: '/images/preview.png',
    title: 'Five Palms 19',
    price: 49.923,
    share: 1,
    type: 'rent',
  },
  {
    image: '/images/preview.png',
    title: 'Five Palms 20',
    price: 49.923,
    share: 1,
    type: 'object',
  },
];
